export const useCountries = () => {
    const countries = [
        { code: "AFG", name: "Afghanistan", currency: "AFN" },
        { code: "ALB", name: "Albanie", currency: "ALL" },
        { code: "DZA", name: "Algérie", currency: "DZD" },
        { code: "AND", name: "Andorre", currency: "EUR" },
        { code: "AGO", name: "Angola", currency: "AOA" },
        { code: "ARG", name: "Argentine", currency: "ARS" },
        { code: "ARM", name: "Arménie", currency: "AMD" },
        { code: "AUS", name: "Australie", currency: "AUD" },
        { code: "AUT", name: "Autriche", currency: "EUR" },
        { code: "AZE", name: "Azerbaïdjan", currency: "AZN" },
        { code: "BHS", name: "Bahamas", currency: "BSD" },
        { code: "BHR", name: "Bahreïn", currency: "BHD" },
        { code: "BGD", name: "Bangladesh", currency: "BDT" },
        { code: "BRB", name: "Barbade", currency: "BBD" },
        { code: "BEL", name: "Belgique", currency: "EUR" },
        { code: "BLZ", name: "Belize", currency: "BZD" },
        { code: "BEN", name: "Bénin", currency: "XOF" },
        { code: "BTN", name: "Bhoutan", currency: "BTN" },
        { code: "BLR", name: "Biélorussie", currency: "BYN" },
        { code: "MMR", name: "Birmanie", currency: "MMK" },
        { code: "BOL", name: "Bolivie", currency: "BOB" },
        { code: "BIH", name: "Bosnie-Herzégovine", currency: "BAM" },
        { code: "BWA", name: "Botswana", currency: "BWP" },
        { code: "BRA", name: "Brésil", currency: "BRL" },
        { code: "BRN", name: "Brunei", currency: "BND" },
        { code: "BGR", name: "Bulgarie", currency: "BGN" },
        { code: "BFA", name: "Burkina Faso", currency: "XOF" },
        { code: "BDI", name: "Burundi", currency: "BIF" },
        { code: "KHM", name: "Cambodge", currency: "KHR" },
        { code: "CMR", name: "Cameroun", currency: "XAF" },
        { code: "CAN", name: "Canada", currency: "CAD" },
        { code: "CPV", name: "Cap-Vert", currency: "CVE" },
        { code: "CAF", name: "Centrafrique", currency: "XAF" },
        { code: "CHL", name: "Chili", currency: "CLP" },
        { code: "CHN", name: "Chine", currency: "CNY" },
        { code: "CYP", name: "Chypre", currency: "EUR" },
        { code: "COL", name: "Colombie", currency: "COP" },
        { code: "COM", name: "Comores", currency: "KMF" },
        { code: "COG", name: "Congo", currency: "XAF" },
        { code: "COD", name: "Congo (RDC)", currency: "CDF" },
        { code: "KOR", name: "Corée du Sud", currency: "KRW" },
        { code: "PRK", name: "Corée du Nord", currency: "KPW" },
        { code: "CRI", name: "Costa Rica", currency: "CRC" },
        { code: "CIV", name: "Côte d'Ivoire", currency: "XOF" },
        { code: "HRV", name: "Croatie", currency: "EUR" },
        { code: "CUB", name: "Cuba", currency: "CUP" },
        { code: "DNK", name: "Danemark", currency: "DKK" },
        { code: "DJI", name: "Djibouti", currency: "DJF" },
        { code: "DOM", name: "Dominique", currency: "XCD" },
        { code: "EGY", name: "Égypte", currency: "EGP" },
        { code: "ARE", name: "Émirats arabes unis", currency: "AED" },
        { code: "ECU", name: "Équateur", currency: "USD" },
        { code: "ERI", name: "Érythrée", currency: "ERN" },
        { code: "ESP", name: "Espagne", currency: "EUR" },
        { code: "EST", name: "Estonie", currency: "EUR" },
        { code: "USA", name: "États-Unis", currency: "USD" },
        { code: "ETH", name: "Éthiopie", currency: "ETB" },
        { code: "FJI", name: "Fidji", currency: "FJD" },
        { code: "FIN", name: "Finlande", currency: "EUR" },
        { code: "FRA", name: "France", currency: "EUR" },
        { code: "GAB", name: "Gabon", currency: "XAF" },
        { code: "GMB", name: "Gambie", currency: "GMD" },
        { code: "GEO", name: "Géorgie", currency: "GEL" },
        { code: "GHA", name: "Ghana", currency: "GHS" },
        { code: "GRC", name: "Grèce", currency: "EUR" },
        { code: "GRD", name: "Grenade", currency: "XCD" },
        { code: "GTM", name: "Guatemala", currency: "GTQ" },
        { code: "GIN", name: "Guinée", currency: "GNF" },
        { code: "GNB", name: "Guinée-Bissau", currency: "XOF" },
        { code: "GNQ", name: "Guinée équatoriale", currency: "XAF" },
        { code: "GUY", name: "Guyana", currency: "GYD" },
        { code: "HTI", name: "Haïti", currency: "HTG" },
        { code: "HND", name: "Honduras", currency: "HNL" },
        { code: "HUN", name: "Hongrie", currency: "HUF" },
        { code: "IND", name: "Inde", currency: "INR" },
        { code: "IDN", name: "Indonésie", currency: "IDR" },
        { code: "IRQ", name: "Irak", currency: "IQD" },
        { code: "IRN", name: "Iran", currency: "IRR" },
        { code: "IRL", name: "Irlande", currency: "EUR" },
        { code: "ISL", name: "Islande", currency: "ISK" },
        { code: "ISR", name: "Israël", currency: "ILS" },
        { code: "ITA", name: "Italie", currency: "EUR" },
        { code: "JAM", name: "Jamaïque", currency: "JMD" },
        { code: "JPN", name: "Japon", currency: "JPY" },
        { code: "JOR", name: "Jordanie", currency: "JOD" },
        { code: "KAZ", name: "Kazakhstan", currency: "KZT" },
        { code: "KEN", name: "Kenya", currency: "KES" },
        { code: "KGZ", name: "Kirghizistan", currency: "KGS" },
        { code: "KIR", name: "Kiribati", currency: "AUD" },
        { code: "KWT", name: "Koweït", currency: "KWD" },
        { code: "LAO", name: "Laos", currency: "LAK" },
        { code: "LSO", name: "Lesotho", currency: "LSL" },
        { code: "LVA", name: "Lettonie", currency: "EUR" },
        { code: "LBN", name: "Liban", currency: "LBP" },
        { code: "LBR", name: "Liberia", currency: "LRD" },
        { code: "LBY", name: "Libye", currency: "LYD" },
        { code: "LIE", name: "Liechtenstein", currency: "CHF" },
        { code: "LTU", name: "Lituanie", currency: "EUR" },
        { code: "LUX", name: "Luxembourg", currency: "EUR" },
        { code: "MKD", name: "Macédoine du Nord", currency: "MKD" },
        { code: "MDG", name: "Madagascar", currency: "MGA" },
        { code: "MYS", name: "Malaisie", currency: "MYR" },
        { code: "MWI", name: "Malawi", currency: "MWK" },
        { code: "MDV", name: "Maldives", currency: "MVR" },
        { code: "MLI", name: "Mali", currency: "XOF" },
        { code: "MLT", name: "Malte", currency: "EUR" },
        { code: "MAR", name: "Maroc", currency: "MAD" },
        { code: "MHL", name: "Marshall", currency: "USD" },
        { code: "MUS", name: "Maurice", currency: "MUR" },
        { code: "MRT", name: "Mauritanie", currency: "MRU" },
        { code: "MEX", name: "Mexique", currency: "MXN" },
        { code: "FSM", name: "Micronésie", currency: "USD" },
        { code: "MDA", name: "Moldavie", currency: "MDL" },
        { code: "MCO", name: "Monaco", currency: "EUR" },
        { code: "MNG", name: "Mongolie", currency: "MNT" },
        { code: "MNE", name: "Monténégro", currency: "EUR" },
        { code: "MOZ", name: "Mozambique", currency: "MZN" },
        { code: "NAM", name: "Namibie", currency: "NAD" },
        { code: "NRU", name: "Nauru", currency: "AUD" },
        { code: "NPL", name: "Népal", currency: "NPR" },
        { code: "NIC", name: "Nicaragua", currency: "NIO" },
        { code: "NER", name: "Niger", currency: "XOF" },
        { code: "NGA", name: "Nigeria", currency: "NGN" },
        { code: "NOR", name: "Norvège", currency: "NOK" },
        { code: "NZL", name: "Nouvelle-Zélande", currency: "NZD" },
        { code: "OMN", name: "Oman", currency: "OMR" },
        { code: "UGA", name: "Ouganda", currency: "UGX" },
        { code: "UZB", name: "Ouzbékistan", currency: "UZS" },
        { code: "PAK", name: "Pakistan", currency: "PKR" },
        { code: "PLW", name: "Palaos", currency: "USD" },
        { code: "PSE", name: "Palestine", currency: "ILS" },
        { code: "PAN", name: "Panama", currency: "PAB" },
        { code: "PNG", name: "Papouasie-Nouvelle-Guinée", currency: "PGK" },
        { code: "PRY", name: "Paraguay", currency: "PYG" },
        { code: "NLD", name: "Pays-Bas", currency: "EUR" },
        { code: "PER", name: "Pérou", currency: "PEN" },
        { code: "PHL", name: "Philippines", currency: "PHP" },
        { code: "POL", name: "Pologne", currency: "PLN" },
        { code: "PRT", name: "Portugal", currency: "EUR" },
        { code: "QAT", name: "Qatar", currency: "QAR" },
        { code: "ROU", name: "Roumanie", currency: "RON" },
        { code: "GBR", name: "Royaume-Uni", currency: "GBP" },
        { code: "RUS", name: "Russie", currency: "RUB" },
        { code: "RWA", name: "Rwanda", currency: "RWF" },
        { code: "KNA", name: "Saint-Christophe-et-Niévès", currency: "XCD" },
        { code: "SMR", name: "Saint-Marin", currency: "EUR" },
        { code: "VCT", name: "Saint-Vincent-et-les-Grenadines", currency: "XCD" },
        { code: "LCA", name: "Sainte-Lucie", currency: "XCD" },
        { code: "SLB", name: "Salomon", currency: "SBD" },
        { code: "SLV", name: "Salvador", currency: "USD" },
        { code: "WSM", name: "Samoa", currency: "WST" },
        { code: "STP", name: "Sao Tomé-et-Principe", currency: "STN" },
        { code: "SEN", name: "Sénégal", currency: "XOF" },
        { code: "SRB", name: "Serbie", currency: "RSD" },
        { code: "SYC", name: "Seychelles", currency: "SCR" },
        { code: "SLE", name: "Sierra Leone", currency: "SLL" },
        { code: "SGP", name: "Singapour", currency: "SGD" },
        { code: "SVK", name: "Slovaquie", currency: "EUR" },
        { code: "SVN", name: "Slovénie", currency: "EUR" },
        { code: "SOM", name: "Somalie", currency: "SOS" },
        { code: "SDN", name: "Soudan", currency: "SDG" },
        { code: "SSD", name: "Soudan du Sud", currency: "SSP" },
        { code: "LKA", name: "Sri Lanka", currency: "LKR" },
        { code: "SWE", name: "Suède", currency: "SEK" },
        { code: "CHE", name: "Suisse", currency: "CHF" },
        { code: "SUR", name: "Suriname", currency: "SRD" },
        { code: "SYR", name: "Syrie", currency: "SYP" },
        { code: "TJK", name: "Tadjikistan", currency: "TJS" },
        { code: "TZA", name: "Tanzanie", currency: "TZS" },
        { code: "TCD", name: "Tchad", currency: "XAF" },
        { code: "CZE", name: "Tchéquie", currency: "CZK" },
        { code: "THA", name: "Thaïlande", currency: "THB" },
        { code: "TLS", name: "Timor oriental", currency: "USD" },
        { code: "TGO", name: "Togo", currency: "XOF" },
        { code: "TON", name: "Tonga", currency: "TOP" },
        { code: "TTO", name: "Trinité-et-Tobago", currency: "TTD" },
        { code: "TUN", name: "Tunisie", currency: "TND" },
        { code: "TKM", name: "Turkménistan", currency: "TMT" },
        { code: "TUR", name: "Turquie", currency: "TRY" },
        { code: "TUV", name: "Tuvalu", currency: "AUD" },
        { code: "UKR", name: "Ukraine", currency: "UAH" },
        { code: "URY", name: "Uruguay", currency: "UYU" },
        { code: "VUT", name: "Vanuatu", currency: "VUV" },
        { code: "VAT", name: "Vatican", currency: "EUR" },
        { code: "VEN", name: "Venezuela", currency: "VES" },
        { code: "VNM", name: "Vietnam", currency: "VND" },
        { code: "YEM", name: "Yémen", currency: "YER" },
        { code: "ZMB", name: "Zambie", currency: "ZMW" },
        { code: "ZWE", name: "Zimbabwe", currency: "USD" }
    ];

    const getCurrencyByCountry = (countryCode: string) => {
        const country = countries.find(c => c.code === countryCode);
        return country ? country.currency : 'USD';
    };

    return {
        countries,
        getCurrencyByCountry
    };
};
