package grpc

import (
	"context"
	"log"
	"net"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"

	"github.com/crypto-bank/microservices-financial-app/services/admin-service/internal/repository"
)

// Server wraps the gRPC server and its services
type Server struct {
	grpcServer    *grpc.Server
	configService *ConfigService
	queryService  *QueryService
	listener      net.Listener
}

// NewServer creates a new gRPC server
func NewServer(repo *repository.AdminRepository) *Server {
	opts := []grpc.ServerOption{
		grpc.UnaryInterceptor(loggingInterceptor),
	}

	grpcServer := grpc.NewServer(opts...)

	configService := NewConfigService(repo)
	queryService := NewQueryService(repo)

	// Register services
	RegisterAdminConfigServiceServer(grpcServer, configService)
	RegisterAdminQueryServiceServer(grpcServer, queryService)

	// Enable reflection for grpcurl and debugging
	reflection.Register(grpcServer)

	return &Server{
		grpcServer:    grpcServer,
		configService: configService,
		queryService:  queryService,
	}
}

// Start starts the gRPC server on the given port
func (s *Server) Start(port string) error {
	listener, err := net.Listen("tcp", ":"+port)
	if err != nil {
		return err
	}
	s.listener = listener

	log.Printf("[gRPC] Admin service gRPC server starting on port %s", port)

	go func() {
		if err := s.grpcServer.Serve(listener); err != nil {
			log.Printf("[gRPC] Server error: %v", err)
		}
	}()

	return nil
}

// Stop gracefully stops the gRPC server
func (s *Server) Stop() {
	log.Println("[gRPC] Stopping gRPC server...")
	s.grpcServer.GracefulStop()
	if s.listener != nil {
		s.listener.Close()
	}
}

// loggingInterceptor logs gRPC requests
func loggingInterceptor(
	ctx context.Context,
	req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (interface{}, error) {
	start := time.Now()

	resp, err := handler(ctx, req)

	log.Printf("[gRPC] %s | %v | err=%v", info.FullMethod, time.Since(start), err)

	return resp, err
}

// Placeholder interfaces - these would be generated by protoc
// In production, run: protoc --go_out=. --go-grpc_out=. proto/admin.proto

type AdminConfigServiceServer interface {
	GetConfiguration(context.Context, *GetConfigRequest) (*ConfigResponse, error)
	GetAllConfigurations(context.Context, *GetAllConfigsRequest) (*ConfigListResponse, error)
	GetConfigurationsByPrefix(context.Context, *GetConfigsByPrefixRequest) (*ConfigListResponse, error)
	IsFeatureEnabled(context.Context, *FeatureRequest) (*FeatureResponse, error)
	GetFee(context.Context, *GetFeeRequest) (*FeeResponse, error)
	GetLimit(context.Context, *GetLimitRequest) (*LimitResponse, error)
}

type AdminQueryServiceServer interface {
	GetDashboardStats(context.Context, *EmptyRequest) (*DashboardStatsResponse, error)
	GetUserStatus(context.Context, *GetUserStatusRequest) (*UserStatusResponse, error)
	GetUserKYCStatus(context.Context, *GetUserStatusRequest) (*KYCStatusResponse, error)
	GetWalletStatus(context.Context, *GetWalletStatusRequest) (*WalletStatusResponse, error)
	GetPlatformAccounts(context.Context, *EmptyRequest) (*PlatformAccountsResponse, error)
	GetHotWallets(context.Context, *EmptyRequest) (*HotWalletsResponse, error)
}

// Placeholder functions for registering - would be generated by protoc
func RegisterAdminConfigServiceServer(s *grpc.Server, srv *ConfigService) {
	// Would be generated code
}

func RegisterAdminQueryServiceServer(s *grpc.Server, srv *QueryService) {
	// Would be generated code
}

// ========== Message Types (would be generated by protoc) ==========

type GetConfigRequest struct {
	Key string
}

type ConfigResponse struct {
	Key              string
	Name             string
	Description      string
	Type             string
	FixedAmount      float64
	PercentageAmount float64
	Currency         string
	IsEnabled        bool
	UpdatedAt        string
	UpdatedBy        string
}

type GetAllConfigsRequest struct {
	Service string
	Limit   int32
	Offset  int32
}

type ConfigListResponse struct {
	Configurations []*ConfigResponse
	Total          int32
}

type GetConfigsByPrefixRequest struct {
	Prefix string
}

type FeatureRequest struct {
	FeatureKey string
}

type FeatureResponse struct {
	IsEnabled bool
}

type GetFeeRequest struct {
	FeeKey   string
	Currency string
}

type FeeResponse struct {
	FeeKey           string
	Type             string
	FixedAmount      float64
	PercentageAmount float64
	Currency         string
	IsEnabled        bool
}

type GetLimitRequest struct {
	LimitKey string
	KycLevel int32
}

type LimitResponse struct {
	LimitKey    string
	LimitAmount float64
	Currency    string
	TierName    string
}

type EmptyRequest struct{}

type DashboardStatsResponse struct {
	TotalUsers        int64
	TotalWallets      int64
	TotalTransactions int64
	PendingKyc        int64
	ActiveCards       int64
	TotalVolume24h    float64
	Currency          string
}

type GetUserStatusRequest struct {
	UserId string
}

type UserStatusResponse struct {
	UserId        string
	Email         string
	Status        string
	KycLevel      int32
	KycStatus     string
	IsBlocked     bool
	BlockedReason string
	CreatedAt     string
}

type KYCStatusResponse struct {
	UserId    string
	KycLevel  int32
	KycStatus string
	Documents []*KYCDocument
}

type KYCDocument struct {
	Id         string
	Type       string
	Status     string
	UploadedAt string
}

type GetWalletStatusRequest struct {
	WalletId string
}

type WalletStatusResponse struct {
	WalletId         string
	UserId           string
	Currency         string
	WalletType       string
	Status           string
	Balance          float64
	AvailableBalance float64
}

type PlatformAccountsResponse struct {
	Accounts []*PlatformAccount
}

type PlatformAccount struct {
	Id       string
	Name     string
	Type     string
	Currency string
	Balance  float64
}

type HotWalletsResponse struct {
	Wallets []*HotWallet
}

type HotWallet struct {
	Id       string
	Currency string
	Address  string
	Balance  float64
	Provider string
}
