_format_version: "3.0"
services:
  - name: auth-service
    url: http://auth-service:8081
    routes:
      - name: auth-routes
        paths:
          - /auth-service
        strip_path: true

  - name: wallet-service
    url: http://wallet-service:8083
    routes:
      - name: wallet-routes
        paths:
          - /wallet-service
        strip_path: true

  - name: card-service
    url: http://card-service:8086
    routes:
      - name: card-routes
        paths:
          - /card-service
        strip_path: true

  - name: transfer-service
    url: http://transfer-service:8084
    routes:
      - name: transfer-routes
        paths:
          - /transfer-service
        strip_path: true

  - name: exchange-service
    url: http://exchange-service:8085
    routes:
      - name: exchange-routes
        paths:
          - /exchange-service
        strip_path: true

  - name: notification-service
    url: http://notification-service:8087
    routes:
      - name: notification-routes
        paths:
          - /notification-service
        strip_path: true

  - name: admin-service
    url: http://admin-service:8088
    routes:
      - name: admin-routes
        paths:
          - /admin-service
        strip_path: true

  - name: support-service
    url: http://support-service:8089
    routes:
      - name: support-routes
        paths:
          - /support-service
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Origin
        - Content-Type
        - Accept
        - Authorization
        - X-Requested-With
      exposed_headers:
        - Authorization
        - Content-Length
      credentials: true
      max_age: 3600
  - name: request-size-limiting
    config:
      allowed_payload_size: 50
      size_unit: megabytes
      require_content_length: false
